spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/harry418/spring-cloud-config-server.git
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"   # Expose all actuator endpoints

server:
  port: 8888


  