spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/your-github-username/config-repo.git
          default-label: main

server:
  port: 8888


  